# Generated by Django 4.2.1 on 2023-05-13 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fabrication',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=255)),
                ('raw_material', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=100)),
                ('in_date', models.DateField(auto_now_add=True)),
                ('out_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('item', 'raw_material', 'quantity', 'in_date')},
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_code', models.CharField(max_length=150, unique=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('model_number', models.CharField(blank=True, max_length=50, null=True)),
                ('machine_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubAssembly',
            fields=[
                ('assembly_id', models.AutoField(primary_key=True, serialize=False)),
                ('process', models.CharField(max_length=255)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('fabrication', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manufactory.fabrication', verbose_name='Related Fabrication')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufactory.machine')),
            ],
        ),
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufactory.machine')),
                ('subassembly', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manufactory.subassembly', verbose_name='Reverse SubAssembly')),
            ],
        ),
    ]
