# Generated by Django 4.2.1 on 2023-05-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('process_id', models.AutoField(primary_key=True, serialize=False)),
                ('process', models.CharField(max_length=255)),
                ('machine_id', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fabrication',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=255)),
                ('raw_material', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('in_date', models.DateField(auto_now_add=True)),
                ('out_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubAssembly',
            fields=[
                ('assembly_id', models.AutoField(primary_key=True, serialize=False)),
                ('process', models.CharField(max_length=255)),
                ('item_id', models.CharField(max_length=50)),
                ('machine_id', models.CharField(max_length=50)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
