# Generated by Django 4.2.1 on 2023-05-13 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manufactory", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="fabrication",
            unique_together={
                ("item", "raw_material", "quantity", "in_date", "out_date")
            },
        ),
    ]
