# Generated by Django 4.2.1 on 2023-05-12 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manufactory", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subassembly",
            old_name="fibrication",
            new_name="fabrication",
        ),
    ]
