# Generated by Django 4.2.1 on 2023-05-12 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("manufactory", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assembly",
            name="process_id",
        ),
        migrations.RemoveField(
            model_name="subassembly",
            name="item_id",
        ),
        migrations.AddField(
            model_name="assembly",
            name="subassembly",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="manufactory.subassembly",
                verbose_name="Reverse SubAssembly",
            ),
        ),
        migrations.AddField(
            model_name="subassembly",
            name="fibrication",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="manufactory.fabrication",
                verbose_name="Related Fabrication",
            ),
        ),
        migrations.AlterField(
            model_name="assembly",
            name="machine_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
