# Generated by Django 4.2.1 on 2023-05-13 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manufactory", "0002_alter_fabrication_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="subassembly",
            unique_together={
                ("fabrication", "process", "machine", "start_date", "end_date")
            },
        ),
    ]
