# Generated by Django 4.2.1 on 2023-05-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufactory", "0002_remove_assembly_process_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fabrication",
            name="quantity",
            field=models.CharField(max_length=100),
        ),
    ]
