# Generated by Django 4.2.1 on 2023-05-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufactory", "0004_alter_assembly_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="assembly",
            name="redundent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="fabrication",
            name="is_available",
            field=models.BooleanField(
                default=True, help_text="Is available for use by Sub-Assembly"
            ),
        ),
        migrations.AddField(
            model_name="fabrication",
            name="redundent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subassembly",
            name="is_available",
            field=models.BooleanField(
                default=True, help_text="Is available for use by ssembly"
            ),
        ),
        migrations.AddField(
            model_name="subassembly",
            name="redundent",
            field=models.BooleanField(default=False),
        ),
    ]
