# Generated by Django 4.2.1 on 2023-05-13 08:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufactory", "0005_assembly_redundent_fabrication_is_available_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assembly",
            name="start_date",
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="fabrication",
            name="in_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="subassembly",
            name="start_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
