# Generated by Django 4.2.1 on 2023-05-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "manufactory",
            "0006_alter_assembly_start_date_alter_fabrication_in_date_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="fabrication",
            name="stamped",
            field=models.BooleanField(
                default=False, help_text="Is available for use by Sub-Assembly"
            ),
        ),
    ]
