# Generated by Django 4.2.1 on 2023-05-13 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("manufactory", "0007_fabrication_stamped"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.CharField(max_length=255)),
                ("raw_material", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Process",
            fields=[
                ("process_id", models.AutoField(primary_key=True, serialize=False)),
                ("process_name", models.CharField(max_length=255)),
                ("process_description", models.TextField(blank=True, null=True)),
                (
                    "process_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="fabrication",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="fabrication",
            name="item_material",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="manufactory.itemmodel",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="assembly",
            name="process",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="manufactory.process"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fabrication",
            unique_together={("item_material", "quantity", "in_date", "out_date")},
        ),
        migrations.RemoveField(
            model_name="fabrication",
            name="item",
        ),
        migrations.RemoveField(
            model_name="fabrication",
            name="raw_material",
        ),
    ]
